apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Release.Name }}-backendconfig
  labels:
    app: {{ .Release.Name }}
    name: {{ .Release.Name }}
spec:
  healthCheck:
    # Jupyter responds with code 302 on "/" which the default healthcheck path,
    # so override it with something that is known to respond 200 without authentication.
    requestPath: "/api"
