apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels: &SdkServiceLabels
    app: {{ .Release.Name }}
    name: {{ .Release.Name }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ .Release.Name }}-backendconfig"}'
spec:
  selector: *SdkServiceLabels
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP
