{{- if not .Values.worker.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-worker-secret
  labels:
    app: "{{ .Release.Name }}"
    name: "{{ .Release.Name }}"
    component: worker
type: Opaque
data:
{{- $tplConfig  := .Values.worker.tplConfig -}}
{{- range $k, $v := .Values.worker.envRenderSecret }}
  {{- if $tplConfig }}
  {{ $k }}: {{ tpl $v $ | b64enc | quote }}
  {{- else }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
