apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flower
  labels: &FlowerDeploymentLabels
    app: "{{ .Release.Name }}"
    name: "{{ .Release.Name }}"
    component: flower
spec:
  selector:
    matchLabels: *FlowerDeploymentLabels
  replicas: 1
  template:
    metadata:
      labels: *FlowerDeploymentLabels
    spec:
      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.containerSecurityContext | nindent 8 }}
      {{- end }}
      serviceAccountName: "{{ .Values.serviceAccount }}"
      containers:
        - name: flower
          image: "{{ .Values.flower.image.repository }}:{{ .Values.flower.image.tag }}"
          command:
            - celery --broker=redis://redis:6379 flower
          ports:
            - name: http
              containerPort: 5555
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 30
            # 1 seconds * 180 = 3 minutes
            failureThreshold: 180
          readinessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 30
            # 1 seconds * 180 = 3 minutes
            failureThreshold: 180
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
