apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flower-service
  labels: &FlowerServiceLabels
    app: {{ .Release.Name }}
    name: {{ .Release.Name }}
    component: flower
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ .Release.Name }}-backendconfig"}'
spec:
  selector: *FlowerServiceLabels
  ports:
    - name: http
      protocol: TCP
      port: 5555
      targetPort: 5555
  type: ClusterIP
