apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-secret
  labels:
    app: {{ .Release.Name }}
    name: {{ .Release.Name }}
    component: redis
type: Opaque
data:
  redis-password: {{ .Values.redis.password | b64enc | quote }}
